# Generated by Django 4.2.23 on 2025-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('average_salary', models.IntegerField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Статистика средней зарплаты по городам для данной вакансии',
                'verbose_name_plural': 'Статистика средней зарплаты по городам для данной вакансии',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='CityShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('share', models.FloatField(verbose_name='Доля')),
            ],
            options={
                'verbose_name': 'Статистика доли вакансий по городам для данной вакансии',
                'verbose_name_plural': 'Статистика доли вакансий по городам для данной вакансии',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='CountVacanciesYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.IntegerField(null=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Статистика количества данной вакансии по годам',
                'verbose_name_plural': 'Статистика количества данной вакансии по годам',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='GeneralCitySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('average_salary', models.IntegerField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Общая статистика средней зарплаты по городам',
                'verbose_name_plural': 'Общая статистика средней зарплаты по городам',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='GeneralCityShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('share', models.FloatField(verbose_name='Доля')),
            ],
            options={
                'verbose_name': 'Общая статистика доли вакансий по городам',
                'verbose_name_plural': 'Общая статистика доли вакансий по городам',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='GeneralCountVacanciesYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.IntegerField(null=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Общая статистика количества вакансий по годам',
                'verbose_name_plural': 'Общая статистика количества вакансий по годам',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSalariesYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.IntegerField(null=True, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Общая статистика средней зарплаты по годам',
                'verbose_name_plural': 'Общая статистика средней зарплаты по годам',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSkillFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('frequency', models.IntegerField(verbose_name='Частота')),
            ],
            options={
                'verbose_name': 'Общая статистика топ навыков по годам',
                'verbose_name_plural': 'Общая статистика топ навыков по годам',
                'ordering': ['year', 'frequency'],
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=20, verbose_name='Text')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Графики статистики',
                'verbose_name_plural': 'Графики статистики',
            },
        ),
        migrations.CreateModel(
            name='SalariesYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.IntegerField(null=True, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Статистика средней зарплаты по годам для данной вакансии',
                'verbose_name_plural': 'Статистика средней зарплаты по годам для данной вакансии',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='SkillFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill', models.CharField(max_length=100, verbose_name='Навык')),
                ('frequency', models.IntegerField(verbose_name='Частота')),
            ],
            options={
                'verbose_name': 'Статистика топ навыков по годам для данной вакансии',
                'verbose_name_plural': 'Статистика топ навыков по годам для данной вакансии',
                'ordering': ['year', 'frequency'],
            },
        ),
    ]
